fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    augeasproviders_core:
      repo: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
    network:
      repo: https://github.com/example42/puppet-network.git
    yum:
      repo: https://github.com/voxpupuli/puppet-yum.git
  symlinks:
    infiniband: "#{source_dir}"
